name: dbt CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dbt-parse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Install packages
        run: dbt deps

      - name: Parse project
        run: dbt parse